services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: shunya-agent-assist-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-ws://localhost:8000}
      - NEXT_PUBLIC_DEFAULT_TENANT_ID=${NEXT_PUBLIC_DEFAULT_TENANT_ID:-}
    volumes:
      - .:/app
      - /app/node_modules
      - ./.env.local:/app/.env.local:ro
    command: sh -c "pnpm install && pnpm dev"
